app:
  name: "gatewaysrv"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8080
  log_level: "info"

services:
  account:
    host: "accountsrv"
    port: 8081
  product:
    host: "productsrv"
    port: 8082
  order:
    host: "ordersrv"
    port: 8083
  payment:
    host: "paymentsrv"
    port: 8084

auth:
  jwt_secret: ""  # Set via GATEWAY_AUTH_JWT_SECRET environment variable

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "X-CSRF-Token"
  allowed_credentials: true
  max_age: 3600